#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO_UPDATER.py - Auto-learning System for Command Enhancement

Fitur:
1. Membaca hasil analisis dari speech_history_analyzer.py
2. Auto-update constants.py dengan phrases baru yang paling sering
3. Backup file sebelum update
4. Test update untuk memastikan tidak ada error
"""

import os
import json
import shutil
from datetime import datetime
from typing import Dict, List
from speech_history_analyzer import SpeechHistoryAnalyzer
from constants import MAIN_COMMANDS

class AutoUpdater:
    def __init__(self, constants_file: str = "constants.py"):
        self.constants_file = constants_file
        self.backup_dir = "backups"
        self.suggestions = {}
        self.updates_made = {}
        
        # Create backup directory if not exists
        if not os.path.exists(self.backup_dir):
            os.makedirs(self.backup_dir)
    
    def analyze_and_prepare_updates(self, min_confidence: float = 0.65):
        """
        Analyze speech history dan prepare updates untuk 6 commands
        
        Args:
            min_confidence: Minimal confidence score untuk include suggestion
        """
        print("\n📊 ANALYZING SPEECH HISTORY FOR AUTO-UPDATES")
        print("="*60)
        
        analyzer = SpeechHistoryAnalyzer()
        analyzer.analyze()
        
        suggestions = analyzer.get_suggestions()
        
        if not suggestions:
            print("\n⚠️  No suggestions found in speech history")
            return False
        
        # Filter high-confidence suggestions
        self.suggestions = {}
        for cmd_name, phrase_list in suggestions.items():
            if cmd_name in MAIN_COMMANDS:
                high_confidence = [
                    p for p in phrase_list 
                    if p.get('confidence', 0) >= min_confidence
                ]
                if high_confidence:
                    self.suggestions[cmd_name] = high_confidence
        
        print(f"\n✅ Found {sum(len(v) for v in self.suggestions.values())} high-confidence suggestions")
        
        for cmd_name, suggestions_list in self.suggestions.items():
            print(f"\n{cmd_name}:")
            for suggestion in suggestions_list[:3]:  # Show top 3
                print(f"  • '{suggestion['phrase']}' (confidence: {suggestion['confidence']:.2f})")
        
        return len(self.suggestions) > 0
    
    def backup_constants(self):
        """Backup constants.py sebelum modifikasi"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = os.path.join(
            self.backup_dir,
            f"constants_backup_{timestamp}.py"
        )
        
        try:
            shutil.copy2(self.constants_file, backup_file)
            print(f"\n✅ Backup created: {backup_file}")
            return backup_file
        except Exception as e:
            print(f"❌ Backup failed: {e}")
            return None
    
    def update_constants(self):
        """
        Update constants.py dengan suggestions baru
        
        Strategy:
        1. Add suggestions ke PHONEME_VARIANTS_BY_COMMAND
        2. Jangan modifikasi MAIN_COMMANDS keywords (terlalu berisiko)
        3. Log semua updates untuk audit trail
        """
        print("\n🔄 UPDATING CONSTANTS.PY")
        print("="*60)
        
        if not self.suggestions:
            print("⚠️  No suggestions to update")
            return False
        
        # Read current constants.py
        with open(self.constants_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Strategy: Create new section for auto-learned phrases
        # This is safer than modifying existing keywords
        
        auto_learned_section = self._generate_auto_learned_section()
        
        # Find insertion point (before the closing comments)
        insertion_marker = '\n# Helper functions:'
        if insertion_marker in content:
            new_content = content.replace(
                insertion_marker,
                auto_learned_section + insertion_marker
            )
        else:
            # If marker not found, append before last few lines
            new_content = content
        
        # Write updated content
        try:
            with open(self.constants_file, 'w', encoding='utf-8') as f:
                f.write(new_content)
            
            print(f"✅ Updated {self.constants_file}")
            
            # Verify update
            self._verify_update()
            return True
        
        except Exception as e:
            print(f"❌ Update failed: {e}")
            return False
    
    def _generate_auto_learned_section(self) -> str:
        """Generate section untuk auto-learned phrases"""
        
        section = "\n\n# AUTO-LEARNED PHRASES (Generated by auto_updater.py)\n"
        section += f"# Generated: {datetime.now().isoformat()}\n"
        section += "# These phrases were learned from user speech history\n"
        section += "AUTO_LEARNED_PHRASES = {\n"
        
        for cmd_name, suggestions_list in self.suggestions.items():
            section += f"    '{cmd_name}': [\n"
            
            for suggestion in suggestions_list[:5]:  # Limit to top 5 per command
                phrase = suggestion['phrase'].replace("'", "\\'")
                confidence = suggestion['confidence']
                section += f"        ('{phrase}', {confidence:.2f}),\n"
            
            section += f"    ],\n"
        
        section += "}\n"
        
        return section
    
    def _verify_update(self):
        """Verify update tidak membuat error"""
        print("\n✅ Verifying update...")
        
        try:
            # Try to import updated constants
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "constants_test",
                self.constants_file
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            # Check that 6 commands still exist
            if hasattr(module, 'MAIN_COMMANDS'):
                commands = list(module.MAIN_COMMANDS.keys())
                if len(commands) == 6:
                    print(f"✅ Verification passed: 6 commands intact")
                    return True
        
        except Exception as e:
            print(f"❌ Verification failed: {e}")
            return False
    
    def create_update_report(self, output_file: str = "AUTO_UPDATE_REPORT.md"):
        """Create detailed report tentang updates yang dilakukan"""
        
        report = f"# AUTO-UPDATE REPORT\n\n"
        report += f"**Generated:** {datetime.now().isoformat()}\n\n"
        report += f"## Summary\n"
        report += f"- Total suggestions: {sum(len(v) for v in self.suggestions.values())}\n"
        report += f"- Commands updated: {len(self.suggestions)}\n\n"
        
        report += f"## Detailed Updates\n\n"
        
        for cmd_name, suggestions_list in self.suggestions.items():
            report += f"### {cmd_name}\n\n"
            report += f"**Suggestions Count:** {len(suggestions_list)}\n\n"
            
            report += "| Phrase | Confidence |\n"
            report += "|--------|------------|\n"
            
            for suggestion in suggestions_list[:10]:  # Show top 10
                phrase = suggestion['phrase']
                confidence = suggestion['confidence']
                report += f"| {phrase} | {confidence:.2f} |\n"
            
            if len(suggestions_list) > 10:
                report += f"| ... and {len(suggestions_list) - 10} more | ... |\n"
            
            report += "\n"
        
        report += f"## Backup Information\n"
        report += f"- Backup directory: {self.backup_dir}\n"
        report += f"- Original file: {self.constants_file}\n"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        print(f"\n✅ Report saved to {output_file}")

def run_auto_update():
    """Convenience function untuk jalankan auto-update"""
    
    print("\n🤖 " + "="*58 + " 🤖")
    print("   AUTO-UPDATER: Learning dari Speech History")
    print("🤖 " + "="*58 + " 🤖")
    
    updater = AutoUpdater()
    
    # Step 1: Analyze
    if not updater.analyze_and_prepare_updates(min_confidence=0.70):
        print("\n⚠️  No high-confidence suggestions found. Exiting.")
        return
    
    # Step 2: Backup
    backup_file = updater.backup_constants()
    if not backup_file:
        print("\n❌ Backup failed. Aborting update to prevent data loss.")
        return
    
    # Step 3: Update
    if updater.update_constants():
        print("\n✅ AUTO-UPDATE SUCCESSFUL!")
    else:
        print(f"\n❌ Update failed. Restore from: {backup_file}")
    
    # Step 4: Report
    updater.create_update_report()

if __name__ == "__main__":
    run_auto_update()
